# Generated by Django 3.0.2 on 2020-03-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('img_reader', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='img_reader.Images')),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
